fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: hling ## Your disqus_shortname, e.g. username
language: en
google_search: true ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: ## Use a jQuery-based local search engine, true/false.
google_analytics: UA-80561051-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: false ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: 归档
    directory: archives/
    icon: fa-archive
  - page: 时间线
    directory: timeline/
    icon: fa-book
  - page: about
    directory: about/
    icon: fa-user
  - page: 留言
    directory: comments/
    icon: fa-comments
  - page: atom
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: smilehe
    url: http://www.smilehe.xyz/
  - title:  
    url:  
  - title:  
    url:  

timeline:
  - num: 1
    word: 2016/11/19-博客上线咯
#  - num: 2
#    word: 　
# - num: 3
#    word: 　
# - num: 4
#   word: 　

# Static files
js: js
css: css

# Theme version
version: 0.0.0
